---
title: "La instrumentalización socio-política del Tribunal Constitucional en Chile: un análisis de las redes sociales que  participan en requerimientos de institucionalidad entre 1972 y 2020"

author: "Jan Dimter, Cristóbal Ortiz y Martín Venegas"
date: "01-11-2020"
output:
  html_document:
    df_print: paged
    theme: readable
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: inline
bibliography: input/bib/CSC-Project-Grupo11.bib
csl: input/bib/apa.csl
link-citations: yes
---
# **Introducción**

En la investigación de las problemáticas socio-políticas contemporáneas, uno de los temas de investigación recurrentes ha sido la conflictiva relación entre política y sociedad. Y no ha podido ser de otra manera, pues las llamadas crisis de legitimación [@habermas_legitimation_1975] o crisis de la democracia liberal [@castells_ruptura_2017] han puesto en tela de juicio las formas en que se desarrolla dicha relación a lo largo y ancho del mundo occidental.  Una de las reflexiones recurrentes en torno a las causas de este tipo de conflictos –que producen y a la vez se ven potenciados por la deslegitimación— se orienta a la instrumentalización de la institucionalidad democrática por ciertos grupos sociales para sus propios fines y que, al hacerlo, contribuyen a la deslegitimación de la política y, por tanto, de la democracia representativa. En ello juega un rol fundamental y específico la instrumentalización de la normativa jurídica institucional o simplemente la constitución política de un país, la cual tiene como mayor virtud –o en el caso de su instrumentalización, vicio— el subsumir cualquier cambio político y social a su marco normativo vigente. 

La constitución política chilena de 1980 –de origen autoritario, pero cuyo objetivo es la transición democrática— representa uno de los casos paradigmáticos de instrumentalización. Y lo anterior debido a su propio diseño original, el cual, si bien contempla una transición que tiene por objeto cambiar el régimen autoritario de Pinochet por una democracia, presenta una gran salvedad. Esta se a la impronta autoritaria que la constitución imprime en la correlación de fuerzas políticas venideras: la constitución de 1980 es un enclave autoritario que perdura en democracia [@heiss_por_2020]. Dicha impronta se expresa en mecanismos institucionales de veto y neutralización susceptibles de apropiación por las fuerzas políticas herederas del régimen autoritario, en desmedro de las fuerzas políticas entrantes [@ginsburg__2014]. Todo lo cual ha impedido la deliberación de las mayorías y la soberanía popular en el periodo postdictadura [@garreton_neoliberalismo_2012].

El conflicto anteriormente descrito ha sido ampliamente estudiado en sus causas y elementos. Así, de una parte, ya hemos visto una de las causas que refieren a los mecanismos de veto que permiten a minorías parlamentarias frenar proyectos de cambio a su contraparte mayoritaria en el parlamento e, incluso, al ejecutivo. De otra parte, hay un grupo de estudios que aborda los elementos de la instrumentalización de la constitución, cuyo blanco favorito ha sido el rol del Tribunal Constitucional (TC) y los respectivos requerimientos de inconstitucionalidad por parte de partidos en la revisión de leyes [@atria_constitucion_2013]. En este último tipo de estudios nos queremos enfocar, pues es el principal modo de instrumentalización de la política por ciertos grupos y uno de los últimos en ejercicio [@atria_democracia_2017].

Al respecto, estudios han afirmado que el TC ha sido utilizado por partidos políticos de derecha como mecanismo de veto y neutralización de cambios sociales de corte progresista [@atria_constitucion_2013]. En lo que respecta al tipo de leyes que se busca vetar o neutralizar, saltan a luz aquellas en materia de cambios al sistema de isapres [@coddou_nuevo_2010; @zuniga_declaracion_2011] y educacional [@atria_democracia_2017]. Finalmente, en materia de impulsores de la instrumentalización los estudios fijan su atención a un partido político heredero del ideario del régimen autoritario chileno: la Unión Demócrata Independiente [@atria_democracia_2017; @ginsburg__2014]. 

Pese a estos avances, los estudios no especifican cuál es el tipo de derecha que ha presentado requerimientos, en el entendido que ni siquiera la UDI es un grupo homogéneo, así como tampoco un partido político agota la categoría “derecha”. Asimismo, no se ha logrado identificar una tipología de leyes a las que estos grupos se esmeran en vetar, dando simplemente el rótulo de “derechos sociales” [@bassa_estado_2008] a lo cual la derecha se opone. En suma, si bien existe una idea ampliamente difundida de que el TC es un mecanismo de veto y neutralización favorable a grupos políticos herederos del régimen cívico-militar, no existe una caracterización de estos grupos, ni de las redes sociales mediante las cuales articulan los requerimientos de inconstitucionalidad. En un nivel operativo, podríamos decir que los estudios no se han detenido a analizar las redes de relaciones socio-políticas que permiten la instrumentalización del TC, así como tampoco de la materia sustantiva de las leyes que intenta bloquear la red.

De esta manera, el presente estudio busca dilucidar el entramado social de los arreglos de poder que, en la esfera de la política, recurren al TC con objeto de neutralizar y/o vetar la deliberación socio-política mayoritaria. En concreto se busca responder la pregunta: 
** *¿Cuáles son las redes políticas que se articulan en el proceso de revisión de proyectos de ley, leyes o tratados que han sido declarados inconstitucionales por el Tribunal Constitucional?* **


### **Objetivos e hipótesis**

-	Objetivo general: Identificar las redes políticas dentro del proceso de revisión de proyectos de ley, leyes o tratados que han sido declarados inconstitucionales por el Tribunal Constitucional.

-	Objetivos específicos:
 1.	Identificar grupos políticos que presentan proyectos de ley, leyes o tratados con carácter constitucional.
 2.	Identificar grupos políticos que recurren al Tribunal Constitucional para frenar reformas.
 3.	Identificar los contenidos puestos en requerimiento.

- Hipótesis: 

# **Referencias**